#!/usr/bin/env python3
"""Regenerate the root service worker (sw.js) with a fresh precache list.

Run whenever a game is added or renamed:

    python3 tools/gen_sw_precache.py

The worker itself uses stale-while-revalidate at runtime, so a stale list is
never fatal — this just guarantees every current asset is available on first
offline launch.
"""
from __future__ import annotations

import os
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

# url slug -> static directory, mirroring the routes in gamehub_server.py
GAMES = {
    "bingo": "bingo",
    "bulls-and-cows": "bulls_and_cows",
    "yacht": "yacht",
    "boggle": "boggle",
    "word-find": "word_find",
    "backgammon": "backgammon",
    "find-em": "find_em",
    "tools": "tools",
    "whoami": "whoami",
    "hangman": "hangman",
    "battleship": "battleship",
    "checkers": "checkers",
    "oracle": "oracle",
    "training": "training",
    "2048": "2048",
    "word-guess": "word-guess",
    "minesweeper": "minesweeper",
    "connect-four": "connect-four",
    "memory": "memory",
    "snake": "snake",
    "simon": "simon",
    "sliding-puzzle": "sliding-puzzle",
    "dots-and-boxes": "dots-and-boxes",
}

ROOT_FILES = [
    "/",
    "/app.js",
    "/styles.css",
    "/manifest.webmanifest",
]

TEMPLATE = '''// Generated by tools/gen_sw_precache.py — edit that script, not this list.
// Root service worker: makes every client-side game available offline.
// Strategy: pre-cache all static assets on install; serve navigations
// network-first with a cache fallback, everything else cache-first with a
// background refresh. API/SSE/auth traffic always goes straight to the
// network so remote multiplayer never gets a stale answer.
const VERSION = "gamehub-{version}";
const CACHE_NAME = `gamehub-${{VERSION}}`;
const PRECACHE = {assets};

const SKIP_PREFIXES = ["/api/", "/auth/", "/share/"];
const SKIP_EXACT = ["/healthz"];

self.addEventListener("install", (event) => {{
  event.waitUntil((async () => {{
    const cache = await caches.open(CACHE_NAME);
    await Promise.allSettled(
      PRECACHE.map((url) => cache.add(new Request(url, {{ cache: "reload" }})))
    );
    await self.skipWaiting();
  }})());
}});

self.addEventListener("activate", (event) => {{
  event.waitUntil((async () => {{
    const names = await caches.keys();
    await Promise.all(
      names
        .filter((name) => name.startsWith("gamehub-") && name !== CACHE_NAME)
        .map((name) => caches.delete(name))
    );
    await self.clients.claim();
  }})());
}});

self.addEventListener("fetch", (event) => {{
  const request = event.request;
  if (request.method !== "GET") return;

  const url = new URL(request.url);
  if (url.origin !== location.origin) return;
  if (SKIP_PREFIXES.some((prefix) => url.pathname.startsWith(prefix))) return;
  if (SKIP_EXACT.includes(url.pathname)) return;

  if (request.mode === "navigate") {{
    // Fresh shell when online, cached page (or the hub) when offline.
    event.respondWith(
      fetch(request)
        .then((response) => {{
          if (response.ok) {{
            const copy = response.clone();
            caches.open(CACHE_NAME).then((cache) => cache.put(request, copy));
          }}
          return response;
        }})
        .catch(async () => {{
          const cache = await caches.open(CACHE_NAME);
          return (
            (await cache.match(url.pathname)) ||
            (await cache.match(request)) ||
            (await cache.match("/")) ||
            new Response("Offline and not cached yet.", {{
              status: 503,
              headers: {{ "Content-Type": "text/plain" }},
            }})
          );
        }})
    );
    return;
  }}

  // Static assets: serve from cache instantly, refresh in the background.
  event.respondWith(
    (async () => {{
      const cache = await caches.open(CACHE_NAME);
      const cached = await cache.match(request);
      const network = fetch(request)
        .then((response) => {{
          if (response.ok) {{
            const copy = response.clone();
            cache.put(request, copy);
          }}
          return response;
        }})
        .catch(() => cached || new Response("Offline and not cached.", {{
          status: 503,
          headers: {{ "Content-Type": "text/plain" }},
        }}));
      return cached || network;
    }})()
  );
}});
'''


def collect_assets() -> list[str]:
    assets = list(ROOT_FILES)
    assets.extend(
        f"/shared/{path.relative_to(BASE_DIR / 'shared').as_posix()}"
        for path in sorted((BASE_DIR / "shared").rglob("*"))
        if path.is_file()
    )
    for slug, directory in GAMES.items():
        static_dir = BASE_DIR / directory / "static"
        if not static_dir.is_dir():
            raise SystemExit(f"missing static dir for {slug}: {static_dir}")
        # The navigable page itself — Flask serves it at /{slug}/.
        assets.append(f"/{slug}/")
        assets.extend(
            f"/{slug}/{path.relative_to(static_dir).as_posix()}"
            for path in sorted(static_dir.rglob("*"))
            if path.is_file()
        )
    return assets


def main() -> None:
    assets = collect_assets()
    version = f"v{len(assets)}-{int(os.environ.get('GAMEHUB_SW_EPOCH', 1))}"
    body = TEMPLATE.format(version=version, assets=str(assets))
    (BASE_DIR / "sw.js").write_text(body, encoding="utf-8")
    print(f"wrote sw.js with {len(assets)} precached assets ({version})")


if __name__ == "__main__":
    main()
