#!/usr/bin/env python3
"""Regenerate Boggle's everyday-word list: boggle/static/common.js.

The solo robot used to hunt the entire board dictionary (Webster's Second),
so even the "Casual" tier would race you to things like "iao", "taen" and
"roka". This generator derives an everyday-word list instead, by taking the
frequency-ranked common-English list already shipped with Hangman and keeping
only the entries that are also real board words.

Sources, no network:
    hangman/static/words.js   frequency-ordered common English (rank = order)
    boggle/static/words.js    the board dictionary the solver walks

The output is rank-ordered too, so the client can slice a familiarity band for
each robot tier with a single length check. Run after editing either source:

    python3 tools/gen_boggle_common.py
"""
from __future__ import annotations

import re
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent
COMMON_SOURCE = BASE_DIR / "hangman" / "static" / "words.js"
BOARD_SOURCE = BASE_DIR / "boggle" / "static" / "words.js"
OUTPUT = BASE_DIR / "boggle" / "static" / "common.js"

MIN_LENGTH = 3
MAX_LENGTH = 10

# Tokens the frequency list picked up from month/day abbreviations and web
# boilerplate. They are dictionary entries and rank high, but nobody counts
# "mon", "tue" or "gif" as a word they spotted, so the robot must not play
# them. Real English words that merely double as abbreviations are kept
# (sun, sat, wed, mar, may, con, net, kit, bin, spa, zip, doc, cam, mac, pic
# and friends stay -- a player can plausibly hunt those).
DENY = {
    # Month abbreviations that are not also English words.
    "jan", "feb", "jun", "jul", "aug", "sep", "sept", "oct", "nov", "dec",
    # Weekday abbreviations that are not also English words.
    "mon", "tue", "tues", "thu", "thur", "thurs", "fri",
    # Web-page and software boilerplate.
    "dev", "docs", "gif", "pst", "www", "http", "htm", "html", "com", "org",
    "edu", "gov", "asp", "corp", "approx", "misc", "esp", "est", "ave",
    "reg", "vol", "admin", "min", "sec", "ist", "ing", "iso", "neo", "ser",
    "sen", "sie", "sri", "tri",
}


def board_dictionary() -> set[str]:
    """The 3-10 letter words the board solver can trace."""
    text = BOARD_SOURCE.read_text(encoding="utf-8")
    match = re.search(r"const RAW =\s*`(.*?)`;", text, re.S)
    if not match:
        raise SystemExit(f"could not find the RAW word list in {BOARD_SOURCE}")
    return {
        word
        for word in match.group(1).split("\n")
        if MIN_LENGTH <= len(word) <= MAX_LENGTH
    }


def frequency_ranked_words() -> list[str]:
    """Hangman's common-English list, in its shipped (frequency) order."""
    text = COMMON_SOURCE.read_text(encoding="utf-8")
    match = re.search(r"const WORDS = \[(.*?)\];", text, re.S)
    if not match:
        raise SystemExit(f"could not find the WORDS array in {COMMON_SOURCE}")
    # Order matters: it is the frequency rank the tiers slice on.
    return re.findall(r'"([^"]*)"', match.group(1))


def main() -> None:
    dictionary = board_dictionary()
    ranked = frequency_ranked_words()

    seen: set[str] = set()
    common: list[str] = []
    for word in ranked:
        if word in seen or word in DENY:
            continue
        if not (MIN_LENGTH <= len(word) <= MAX_LENGTH):
            continue
        if word not in dictionary:
            continue
        seen.add(word)
        common.append(word)

    if len(common) < 1000:
        raise SystemExit(f"only {len(common)} everyday words survived; refusing to write")

    body = ",\n".join(f'    "{word}"' for word in common)
    OUTPUT.write_text(
        "// Generated by tools/gen_boggle_common.py - edit that script, not this list.\n"
        "// Everyday English words (most common first) that are also board words.\n"
        "// The solo robot hunts only from this list, so it never plays obscure\n"
        "// dictionary words like \"iao\" or \"roka\" against you.\n"
        "(function (global) {\n"
        '  "use strict";\n'
        "  const WORDS = [\n"
        f"{body},\n"
        "  ];\n"
        "  global.BoggleCommon = { WORDS };\n"
        "})(window);\n",
        encoding="utf-8",
    )
    print(f"wrote {OUTPUT.relative_to(BASE_DIR)} with {len(common)} everyday words")
    print(f"  most common: {' '.join(common[:8])}")
    print(f"  least common: {' '.join(common[-8:])}")


if __name__ == "__main__":
    main()
